name: Build And Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Setup node environment
        uses: actions/setup-node@v4

      - name: Build
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          folder: dist
          branch: gh-pages
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download production artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: dist
