name: Build And Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v2.3.1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install

      - name: Setup node environment
        uses: actions/setup-node@v3

      - name: Build
        run: yarn run build
